// Presentation only: stored preference values remain unchanged.
export const activityEmojis: Record<string, string> = {
  "Art": "🎨",
  "Creativity": "💡",
  "Artists": "🧑‍🎨",
  "Performing Arts": "🎭",
  "Collaboration Between Creative Minds": "🤝",
  "Theater": "🎭",
  "Painting": "🖌️",
  "Local Attractions": "📍",
  "Museum": "🏛️",
  "Entrepreneurship": "🚀",
  "Professional Networking": "🤝",
  "Startup Businesses": "🌱",
  "Business Strategy": "♟️",
  "Professional Development": "📈",
  "Investing": "📊",
  "Leadership": "🧭",
  "Innovation": "💡",
  "Online Marketing": "📣",
  "Professional Women": "👩‍💼",
  "Young Professionals": "💼",
  "Musicians": "🎶",
  "Fashion Design": "🧵",
  "Community Building": "🏘️",
  "Community Service": "🤲",
  "Sustainability": "🌿",
  "Dancing": "💃",
  "Social Dancing": "🪩",
  "Dance Lessons": "👟",
  "Latin Dance": "💃",
  "Salsa": "🕺",
  "Game Night": "🎲",
  "Board Games": "♟️",
  "Games": "🎯",
  "Gaming": "🎮",
  "Card Games": "🃏",
  "Video Games": "🕹️",
  "Wellness": "🌿",
  "Meditation": "🧘",
  "Healthy Living": "🌱",
  "Energy Healing": "✨",
  "Yoga": "🧘",
  "Alternative Medicine": "🍃",
  "Nutrition": "🥑",
  "Healthy Eating": "🥗",
  "Hobbies & Passions": "🧶",
  "Identity & Language": "💬",
  "Music": "🎵",
  "Parents & Family": "🏡",
  "Pets & Animals": "🐾",
  "Religion & Spirituality": "🕊️",
  "Science & Education": "🔬",
  "Social Activities": "🫶",
  "Sports & Fitness": "🏃",
  "Small gatherings": "🕯️",
  "Big events": "🎉",
  "Casual hangouts": "☕",
  "Sport activities": "⚽",
  "Quiet events": "🌙",
  "Thoughtful & deep": "💭",
  "Food & drinks": "🍽️",
  "Talks": "🎙️",
  "Tourism & local attractions": "🗺️",
  "People my age": "👋",
  "Students": "🎓",
  "Professionals": "💼",
  "Other parents": "🏡",
  "Other expats": "🌍",
  "Tech folks": "💻",
  "No preference": "✨",
  "Same-minded people": "🫶",
  "Meet new people": "👋",
  "Try new things": "🧭",
  "Find a date": "💞",
  "Create community": "🏘️",
  "Grow my network": "🤝",
  "Get more active": "🏃",
  "Discover new hobbies": "🎨",
  "Just looking": "👀",
  "Learn something new": "📚"
};
