// Native documents: no embedded browser, remote HTML, or retired website navigation.
export const mobileLegal = {
  privacy: {
    title: 'Privacy Policy',
    sections: [
      ['About this policy', 'Echoocity is committed to protecting your privacy. This policy explains how we handle personal information in our mobile app, including under Canada’s Personal Information Protection and Electronic Documents Act (PIPEDA).'],
      ['Information we collect', 'Account information includes your name, email address, profile photo, username and authentication information. Preferences include interests, event tastes, budget, pace, and optional dietary or allergy information. We process your selected city and, with permission, device location to find nearby places. App activity may include saved routes, planning conversations, check-ins, Link Up activity, and notification preferences.'],
      ['How information is used', 'We use this information to authenticate you, personalize discovery and planning, provide social features you choose to use, maintain app security, and respond to support requests. Location permissions and notifications can be managed through device settings. Optional planning memory and consent choices can be managed in the app.'],
      ['Service providers and subscriptions', 'We use service providers to host data, authenticate accounts, generate planning responses, and supply location and venue information. Relevant planning inputs may be processed by AI and location providers to answer your request. Apple or Google processes subscription payments; Echoocity does not receive your full payment-card details. RevenueCat processes your app account identifier and store purchase information to verify subscription access. Subscription and usage records are stored on our backend to enforce plan limits and prevent abuse.'],
      ['Security and retention', 'We use access controls and encrypted connections to protect information. We retain information as needed to provide the service and meet legal, security, and recordkeeping obligations. You can delete your account from Account & help. Some billing records may remain with Apple, Google, or service providers under their retention requirements. Deleting your app account does not cancel a store subscription.'],
      ['Aggregate city information', 'Subject to your consent choices, anonymised aggregate check-in and activity information may be used for city intelligence reports. These reports should not identify individual users. You can manage your city intelligence consent in your profile.'],
      ['Your choices and contact', 'You may request access to or correction of your personal information, or ask questions about deletion and retention. Contact the Privacy Officer, Idris Oyejobi, at privacy@echoocity.com.'],
    ],
  },
  terms: {
    title: 'Terms of Use',
    sections: [
      ['Using Echoocity', 'By creating an account or using Echoocity, you agree to these terms. Echoocity provides local discovery, route planning and venue recommendations based on regional information and your preferences. Keep your login secure and do not misuse the service, scrape its data, or interfere with other users.'],
      ['Subscriptions', 'A subscription is required for newly registered accounts unless Echoocity explicitly grants access. City Pass and City All-Access are auto-renewable monthly subscriptions. The purchase screen displays the current localized store price and included features before confirmation. Existing accounts granted permanent access do not need to subscribe.'],
      ['Payments, renewal and cancellation', 'Payment is charged to your Apple or Google account when you confirm a purchase. Subscriptions renew automatically unless cancelled at least 24 hours before the current period ends. Your store account is charged for renewal according to the store’s terms. Manage or cancel subscriptions in your Apple or Google subscription settings. Cancellation normally preserves access through the paid period. Refunds are handled through the relevant store under its policies and applicable law. Restore Purchases checks purchases associated with your store account.'],
      ['Usage allowances', 'City Pass includes 10 AI Flow route generations or edits and 100 concierge messages per calendar month. City All-Access includes 50 route generations or edits and 500 concierge messages per calendar month. Allowances reset on the first day of each month at 00:00 UTC and do not roll over. Failed requests are not intended to consume allowances. Short-term rate limits protect service availability. Event tickets, hotel stays, dining, transport and other real-world bookings are not included in the subscription.'],
      ['Recommendation and allergy information', 'AI-generated routes and venue information may be incomplete or outdated. Confirm opening hours, availability, accessibility, prices, and travel conditions before visiting. Dietary and allergy information is a discovery aid, not medical advice. Always confirm dietary requirements directly with the venue. Nothing in these terms excludes rights or liabilities that cannot be excluded under applicable law.'],
      ['Account deletion', 'You can delete your account in Account & help. Account deletion is permanent and removes access grants associated with that account. Deleting the app or account does not cancel your Apple or Google subscription; cancel separately in store settings to stop renewals.'],
      ['Intellectual property and governing law', 'Echoocity’s original branding, templates, designs and editorial content belong to Echoocity or their respective licensors. These terms are governed by the laws of Ontario and applicable federal Canadian law, subject to mandatory consumer rights. For questions, contact privacy@echoocity.com.'],
    ],
  },
};
